name: Code Quality

on:
  workflow_dispatch:
  
defaults:
  run:
    working-directory: react-boilerplate
  
jobs:
  code-quality:
    uses: dpbeaumont/github-actions/.github/workflows/code-quality-template.yml@main
    with:
      working-directory: react-boilerplate
